<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run()
    {
        $this->db->query('SET FOREIGN_KEY_CHECKS=0;');

        $this->db->table('roles')->truncate();
        $data_roles = [
            [
                'id' => '1',
                'role_name' => 'admin',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => '2',
                'role_name' => 'asisten',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => '3',
                'role_name' => 'dosen',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => '4',
                'role_name' => 'praktikan',
                'created_at' => null,
                'updated_at' => null,
            ],
        ];
        $this->db->table('roles')->insertBatch($data_roles);

        $this->db->table('users')->truncate();
        $data_users = [
            [
                'id' => '1',
                'nomor' => '042609780',
                'nama' => 'Dr. Jasman Pardede, S.Si., M.T.',
                'no_telp' => '081234567890',
                'jurusan' => 'Informatika',
                'role_id' => '1',
                'password' => '$2y$12$xs3TIG54dyqby45tJXM6IeDsM24ijA9LNGgT2ewrvNbHow1Fo05JK',
                'foto' => 'uploads/photos/1/1785321488_4eba383a7a8cea0737f0.png',
                'created_at' => '2026-07-22 06:32:43',
                'updated_at' => '2026-07-29 10:38:08',
                'google_scholar' => 'https://scholar.google.com/citations?user=tAYtAPoAAAAJ&hl=id&oi=ao',
                'sinta' => 'https://sinta.kemdiktisaintek.go.id/authors/profile/6007088',
                'orcid' => 'https://orcid.org/0000-0001-7773-0296',
                'scopus' => 'https://www.scopus.com/pages/authors/56532518500',
            ],
            [
                'id' => '6',
                'nomor' => '152022006',
                'nama' => 'Aditya Budi Septiawan',
                'no_telp' => '08123456790',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$y9V5rvvhk4SsPpzCLY/yKO3.3BFe8FXDWKtcD1nz/pqmvXIk7iss6',
                'foto' => 'uploads/photos/6/1785302518_c03d811e0ebb6da370c2.jpeg',
                'created_at' => '2026-07-22 06:32:59',
                'updated_at' => '2026-07-29 05:21:58',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '7',
                'nomor' => '152022007',
                'nama' => 'Aliyya Rahmawati Putri',
                'no_telp' => '08123456791',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$ijepcQnDgpORs1GtLYRRuuTbeMPmVjW5uPSTjqiFZgsrHpTLVCUnC',
                'foto' => 'uploads/photos/AliyyaRahmawatiPutri.jpg',
                'created_at' => '2026-07-22 06:33:00',
                'updated_at' => '2026-07-22 06:33:19',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '8',
                'nomor' => '152022008',
                'nama' => 'Delisya Pramesti Fitriya',
                'no_telp' => '08123456792',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$DYcFSXSB.HB2tA4FDl.owuY7t3G4usXb0c8QqsP7L3uBBrJ6h4P4C',
                'foto' => 'uploads/photos/DelisyaPramestiFitriya.jpg',
                'created_at' => '2026-07-22 06:33:01',
                'updated_at' => '2026-07-22 06:33:19',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '9',
                'nomor' => '152022009',
                'nama' => 'Dindin Imanudin',
                'no_telp' => '08123456793',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$waZAK47ScKKDfwG9a07VBe9WHXk2NcM88Utkj3ZCV4VNu6xMfQiUC',
                'foto' => 'uploads/photos/DindinImanudin.jpg',
                'created_at' => '2026-07-22 06:33:01',
                'updated_at' => '2026-07-22 06:33:19',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '10',
                'nomor' => '152022010',
                'nama' => 'Fathurrahman Pratama Putra',
                'no_telp' => '08123456794',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$lM3IzU9WBjuq25DxPeYKpO063.K4vU8C0Pu7OvTljN2hE2HYvGAlq',
                'foto' => 'uploads/photos/FathurrahmanPratamaPutra.jpg',
                'created_at' => '2026-07-22 06:33:02',
                'updated_at' => '2026-07-22 06:33:20',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '11',
                'nomor' => '152022011',
                'nama' => 'Felix Angga Resky',
                'no_telp' => '08123456795',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$CD2ZDuoExhiUCS9ArWEReOSFfxAY/5tlihoOoyPz8ZTfsvVJklJpK',
                'foto' => 'uploads/photos/FelixAnggaResky.jpg',
                'created_at' => '2026-07-22 06:33:02',
                'updated_at' => '2026-07-22 06:33:20',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '12',
                'nomor' => '152022012',
                'nama' => 'Ghinova Klarisa Irawadi',
                'no_telp' => '08123456796',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$Yn8RAFcxwVZQ41NgvHRn3.MOM.IFrZ9fhxRZgc1LSMw8VsMeWHONq',
                'foto' => 'uploads/photos/GhinovaKlarisaIrawadi.jpg',
                'created_at' => '2026-07-22 06:33:03',
                'updated_at' => '2026-07-22 06:33:20',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '13',
                'nomor' => '152022013',
                'nama' => 'Hikam Hikmatul Huda',
                'no_telp' => '08123456797',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$W0xGXuEdpKAzQdj6frFd7uGZnM2iH/FhVlVKpscz3/OTt7deDB6r6',
                'foto' => 'uploads/photos/HikamHikmatulHuda.jpg',
                'created_at' => '2026-07-22 06:33:04',
                'updated_at' => '2026-07-22 06:33:20',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '14',
                'nomor' => '152022014',
                'nama' => 'Moh Ilyas',
                'no_telp' => '08123456798',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$MX5JM5IFQt.jNq4AzR.rRuyBJh0otNueTAXsSMovTqTqrMw78C8AW',
                'foto' => 'uploads/photos/MohIlyas.jpg',
                'created_at' => '2026-07-22 06:33:04',
                'updated_at' => '2026-07-22 06:33:20',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '15',
                'nomor' => '152022015',
                'nama' => 'Muhamad Rizky',
                'no_telp' => '08123456799',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$St0troGXtexzLPO3ceUKtOFnVq9VOA77fzSMq4NjeSnUA5qiF08Du',
                'foto' => 'uploads/photos/MuhamadRizky.jpg',
                'created_at' => '2026-07-22 06:33:05',
                'updated_at' => '2026-07-22 06:33:21',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '16',
                'nomor' => '152022016',
                'nama' => 'Muhammad Hasby As-shiddiqy',
                'no_telp' => '08123456800',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$2FGsd4eXDzS.EsejmLVWAuFryUcSRoWHbZayLVsI1gWnyrDHfEAV2',
                'foto' => 'uploads/photos/MuhammadHasbyAs-shiddiqy.jpg',
                'created_at' => '2026-07-22 06:33:05',
                'updated_at' => '2026-07-22 06:33:21',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '17',
                'nomor' => '152022017',
                'nama' => 'Muhammad Rifqi Yusufi',
                'no_telp' => '08123456801',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$rV6LMsNN8UUhIm7uoMA01ulUMadBOmEmRPvPbcuhDozm.NeDP.sAW',
                'foto' => 'uploads/photos/MuhammadRifqiYusufi.jpg',
                'created_at' => '2026-07-22 06:33:05',
                'updated_at' => '2026-07-22 06:33:21',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '18',
                'nomor' => '152022018',
                'nama' => 'Nakhwa Ghinayah Rahadatul Aisy',
                'no_telp' => '08123456802',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$m7EOvOezHLWZpTLSdSYwZuMGMOnrqalOBZann9pZRtzExBqJ29n.O',
                'foto' => 'uploads/photos/NakhwaGhinayahRahadatulAisy.jpg',
                'created_at' => '2026-07-22 06:33:06',
                'updated_at' => '2026-07-22 06:33:21',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '19',
                'nomor' => '152022019',
                'nama' => 'Nasywa Adita Zain',
                'no_telp' => '08123456803',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$iPjXsrG2bi1EFwMfF2KfTeaclXELVz2xba/rPAl1masa2ZLyAcH7q',
                'foto' => 'uploads/photos/NasywaAditaZain.jpg',
                'created_at' => '2026-07-22 06:33:06',
                'updated_at' => '2026-07-22 06:33:21',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '20',
                'nomor' => '152022020',
                'nama' => 'Nazwa Nur Salsa Bella',
                'no_telp' => '08123456804',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$B97sNkT1qEL0dsZ1BrvteeqOUCW30/xipK/HRqNfVNjjyjPZ3u6UW',
                'foto' => 'uploads/photos/NazwaNurSalsaBella.jpg',
                'created_at' => '2026-07-22 06:33:07',
                'updated_at' => '2026-07-22 06:33:21',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '21',
                'nomor' => '152022021',
                'nama' => 'Nizar Abdul Malik',
                'no_telp' => '08123456805',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$w6vo.JgdWRxq/yiWjYBdv.gBpUTidkNpdCndGcUuwA9YqhWNds5Rm',
                'foto' => 'uploads/photos/NizarAbdulMalik.jpg',
                'created_at' => '2026-07-22 06:33:07',
                'updated_at' => '2026-07-22 06:33:21',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '22',
                'nomor' => '152022022',
                'nama' => 'Raden Muhammad Ariil Al Hafizh',
                'no_telp' => '08123456806',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$MgdNMWWi6FB05H30xmFaXO5oVFHB34eKiJXeXEjsmEUe4Kk1U6Uj.',
                'foto' => 'uploads/photos/RadenMuhammadAriilAlHafizh.jpg',
                'created_at' => '2026-07-22 06:33:07',
                'updated_at' => '2026-07-22 06:33:21',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '23',
                'nomor' => '152022023',
                'nama' => 'Rizki Saepul Aziz',
                'no_telp' => '08123456807',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$rx/1uaRBpJaQEUWT8MftZeTBxDQbEkMjDnZY1NdB4fWDita8V8GOG',
                'foto' => 'uploads/photos/RizkiSaepulAziz.jpg',
                'created_at' => '2026-07-22 06:33:08',
                'updated_at' => '2026-07-22 06:33:22',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '24',
                'nomor' => '152022024',
                'nama' => 'Sintia Wati',
                'no_telp' => '08123456808',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$6d.vzUCkRZ2QyHGN.E2T/Ohzta7QuUYAiE2lxPDN0hh0gfRQ1rR3.',
                'foto' => 'uploads/photos/SintiaWati.jpg',
                'created_at' => '2026-07-22 06:33:09',
                'updated_at' => '2026-07-29 07:30:30',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '25',
                'nomor' => '152022025',
                'nama' => 'Taras Al Fariz',
                'no_telp' => '08123456809',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$GPMaRSHhxLZjEtAyC4TR3.0OhfuwKD/SQZbfcdEMR5Zk21ZNtr2Ze',
                'foto' => 'uploads/photos/TarasAlFariz.jpg',
                'created_at' => '2026-07-22 06:33:09',
                'updated_at' => '2026-07-22 06:33:23',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '26',
                'nomor' => '152022026',
                'nama' => 'Tedy Sukma Permana',
                'no_telp' => '08123456810',
                'jurusan' => 'Informatika',
                'role_id' => '2',
                'password' => '$2y$12$41exnZIKBpWwCcTeE6BD.eboZRzmF0RXLsCCpS5hM6VCm75gryprK',
                'foto' => 'uploads/photos/TedySukmaPermana.jpg',
                'created_at' => '2026-07-22 06:33:09',
                'updated_at' => '2026-07-22 06:33:23',
                'google_scholar' => null,
                'sinta' => null,
                'orcid' => null,
                'scopus' => null,
            ],
            [
                'id' => '27',
                'nomor' => ' 96557786',
                'nama' => 'Rizka Milandga Milenio, S.Si., M.T',
                'no_telp' => '',
                'jurusan' => 'Informatika',
                'role_id' => '3',
                'password' => '$2y$12$XQbQx1KdeFmkgW96t8J3wOZ7fTGcPX7U2/BZMLacRtY4AMaSNr.T2',
                'foto' => 'uploads/photos/27/1785321449_1a9d2395a3fba7c9e2d1.jpeg',
                'created_at' => '2026-07-29 07:48:20',
                'updated_at' => '2026-07-29 10:37:29',
                'google_scholar' => 'https://scholar.google.com/citations?user=D3rOW7wAAAAJ&hl=en&authuser=2&oi=ao',
                'sinta' => 'https://sinta.kemdiktisaintek.go.id/authors/profile/6979154',
                'orcid' => 'https://orcid.org/0009-0003-0860-5557',
                'scopus' => 'https://www.scopus.com/authid/detail.uri?authorId=60139843300',
            ],
            [
                'id' => '28',
                'nomor' => '11837',
                'nama' => 'ANISA PUTRI SETYANINGRUM S.Kom., M.T.',
                'no_telp' => '',
                'jurusan' => 'Informatika',
                'role_id' => '3',
                'password' => '$2y$12$iDj1MKfuIN7fkIXnbwMPh.mmZszz69IkubVrq7nc6G04jJ9LsA10.',
                'foto' => 'uploads/photos/28/1785485329_dd6f6cd50a35d1515038.jpeg',
                'created_at' => '2026-07-29 07:56:22',
                'updated_at' => '2026-07-31 08:08:49',
                'google_scholar' => 'https://scholar.google.com/citations?user=XHixseoAAAAJ&hl=id',
                'sinta' => 'https://sinta.kemdiktisaintek.go.id/authors/profile/6941557',
                'orcid' => 'http://orcid.org/0009-0002-1640-5507',
                'scopus' => 'https://www.scopus.com/pages/authors/59703254600',
            ],
            [
                'id' => '29',
                'nomor' => '041707820',
                'nama' => 'MARISA PREMITASARI S.T., M.T.',
                'no_telp' => '',
                'jurusan' => 'Informatika',
                'role_id' => '3',
                'password' => '$2y$12$27.jys57o9TFEkvagRH1E.qqEd3m1lFmeeu.iprvR11aUcf/qMheW',
                'foto' => 'uploads/photos/29/1785321395_fe2e14dc4baa0d0c3ebb.png',
                'created_at' => '2026-07-29 08:00:10',
                'updated_at' => '2026-07-29 10:36:35',
                'google_scholar' => 'https://scholar.google.com/citations?user=b6DJvgwAAAAJ&hl=id',
                'sinta' => 'https://sinta.kemdiktisaintek.go.id/authors/profile/137934',
                'orcid' => 'https://orcid.org/0009-0000-5744-2078',
                'scopus' => 'https://www.scopus.com/pages/authors/56725799600',
            ],
            [
                'id' => '30',
                'nomor' => '042211660',
                'nama' => 'ASEP NANA HERMANA S.T., M.T. ',
                'no_telp' => '',
                'jurusan' => 'Informatika',
                'role_id' => '3',
                'password' => '$2y$12$0/Se32QwVSKUX/9s7LmEYOoJfZ1wZ6f/15yHtU3utXrw6tYqPGigW',
                'foto' => 'uploads/photos/30/1785321278_042a1d284c13d6e2f509.png',
                'created_at' => '2026-07-29 08:01:30',
                'updated_at' => '2026-07-29 10:34:38',
                'google_scholar' => '',
                'sinta' => '',
                'orcid' => '',
                'scopus' => '',
            ],
        ];
        $this->db->table('users')->insertBatch($data_users);

        $this->db->table('periode')->truncate();
        $data_periode = [
            [
                'id_periode' => '1',
                'nama_periode' => '2022/2023',
                'tahun' => '2022',
                'status_aktif' => 'tidak aktif',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
            [
                'id_periode' => '2',
                'nama_periode' => '2023/2024',
                'tahun' => '2023',
                'status_aktif' => 'tidak aktif',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
            [
                'id_periode' => '3',
                'nama_periode' => '2024/2025',
                'tahun' => '2024',
                'status_aktif' => 'tidak aktif',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
            [
                'id_periode' => '4',
                'nama_periode' => '2025/2026',
                'tahun' => '2025',
                'status_aktif' => 'tidak aktif',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
            [
                'id_periode' => '5',
                'nama_periode' => 'Ganjil 2026/2027',
                'tahun' => '2026',
                'status_aktif' => 'tidak aktif',
                'created_at' => '2026-07-30 03:50:35',
                'updated_at' => '2026-07-30 03:50:35',
            ],
        ];
        $this->db->table('periode')->insertBatch($data_periode);

        $this->db->table('ruangan')->truncate();
        $data_ruangan = [
            [
                'id_ruangan' => '1',
                'nama_ruangan' => 'Lab Komputer 1',
                'kapasitas' => '40',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
            [
                'id_ruangan' => '2',
                'nama_ruangan' => 'Lab Komputer 2',
                'kapasitas' => '40',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
            [
                'id_ruangan' => '3',
                'nama_ruangan' => 'Lab Komputer 3',
                'kapasitas' => '40',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
            [
                'id_ruangan' => '4',
                'nama_ruangan' => 'Lab Komputer 4',
                'kapasitas' => '40',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
            [
                'id_ruangan' => '5',
                'nama_ruangan' => 'Lab Sistem Cerdas',
                'kapasitas' => '30',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
            [
                'id_ruangan' => '6',
                'nama_ruangan' => 'Lab Data Mining',
                'kapasitas' => '30',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
            [
                'id_ruangan' => '7',
                'nama_ruangan' => 'Lab Komputer 1',
                'kapasitas' => '40',
                'created_at' => '2026-07-22 06:33:14',
                'updated_at' => '2026-07-22 06:33:14',
            ],
            [
                'id_ruangan' => '8',
                'nama_ruangan' => 'Lab Komputer 2',
                'kapasitas' => '40',
                'created_at' => '2026-07-22 06:33:14',
                'updated_at' => '2026-07-22 06:33:14',
            ],
            [
                'id_ruangan' => '9',
                'nama_ruangan' => 'Lab Komputer 3',
                'kapasitas' => '40',
                'created_at' => '2026-07-22 06:33:14',
                'updated_at' => '2026-07-22 06:33:14',
            ],
            [
                'id_ruangan' => '10',
                'nama_ruangan' => 'Lab Komputer 4',
                'kapasitas' => '40',
                'created_at' => '2026-07-22 06:33:14',
                'updated_at' => '2026-07-22 06:33:14',
            ],
            [
                'id_ruangan' => '11',
                'nama_ruangan' => 'Lab Sistem Cerdas',
                'kapasitas' => '30',
                'created_at' => '2026-07-22 06:33:14',
                'updated_at' => '2026-07-22 06:33:14',
            ],
            [
                'id_ruangan' => '12',
                'nama_ruangan' => 'Lab Data Mining',
                'kapasitas' => '30',
                'created_at' => '2026-07-22 06:33:14',
                'updated_at' => '2026-07-22 06:33:14',
            ],
        ];
        $this->db->table('ruangan')->insertBatch($data_ruangan);

        $this->db->table('events')->truncate();
        $data_events = [
            [
                'id_event' => '1',
                'nama_event' => 'Praktikum Machine Learning',
                'deskripsi' => 'Praktikum supervised & unsupervised learning algorithms',
                'jenis' => 'praktikum',
                'created_by' => '1',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-30 03:44:49',
            ],
            [
                'id_event' => '2',
                'nama_event' => 'Deep Learning',
                'deskripsi' => 'Praktikum neural networks dan deep learning architectures',
                'jenis' => 'praktikum',
                'created_by' => '1',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
            [
                'id_event' => '3',
                'nama_event' => 'Expert Systems',
                'deskripsi' => 'Praktikum sistem pakar berbasis rule dan inference engine',
                'jenis' => 'praktikum',
                'created_by' => '1',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
            [
                'id_event' => '4',
                'nama_event' => 'Artificial Intelligence',
                'deskripsi' => 'Praktikum konsep dasar dan aplikasi artificial intelligence',
                'jenis' => 'praktikum',
                'created_by' => '1',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
            [
                'id_event' => '5',
                'nama_event' => 'Smart Systems',
                'deskripsi' => 'Praktikum sistem cerdas untuk IoT dan automation',
                'jenis' => 'praktikum',
                'created_by' => '1',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
            [
                'id_event' => '6',
                'nama_event' => 'Data Mining',
                'deskripsi' => 'Praktikum clustering, classification, dan association rules',
                'jenis' => 'praktikum',
                'created_by' => '1',
                'created_at' => '2026-07-22 06:32:45',
                'updated_at' => '2026-07-22 06:32:45',
            ],
        ];
        $this->db->table('events')->insertBatch($data_events);

        $this->db->table('jadwal')->truncate();
        $data_jadwal = [
            [
                'id_jadwal' => '1',
                'id_event' => '1',
                'tanggal' => '2025-12-02',
                'waktu_mulai' => '08:00:00',
                'waktu_selesai' => '10:00:00',
                'id_ruangan' => '1',
                'kelas' => 'A',
                'created_at' => '2026-07-22 06:32:47',
                'updated_at' => '2026-07-22 06:32:47',
            ],
            [
                'id_jadwal' => '2',
                'id_event' => '1',
                'tanggal' => '2025-12-10',
                'waktu_mulai' => '13:00:00',
                'waktu_selesai' => '15:00:00',
                'id_ruangan' => '5',
                'kelas' => 'B',
                'created_at' => '2026-07-22 06:32:47',
                'updated_at' => '2026-07-30 03:42:49',
            ],
            [
                'id_jadwal' => '3',
                'id_event' => '2',
                'tanggal' => '2025-12-03',
                'waktu_mulai' => '09:00:00',
                'waktu_selesai' => '11:00:00',
                'id_ruangan' => '2',
                'kelas' => 'A',
                'created_at' => '2026-07-22 06:32:47',
                'updated_at' => '2026-07-22 06:32:47',
            ],
            [
                'id_jadwal' => '4',
                'id_event' => '2',
                'tanggal' => '2025-12-10',
                'waktu_mulai' => '14:00:00',
                'waktu_selesai' => '16:00:00',
                'id_ruangan' => '2',
                'kelas' => 'B',
                'created_at' => '2026-07-22 06:32:47',
                'updated_at' => '2026-07-22 06:32:47',
            ],
            [
                'id_jadwal' => '5',
                'id_event' => '3',
                'tanggal' => '2025-12-04',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '12:00:00',
                'id_ruangan' => '3',
                'kelas' => 'A',
                'created_at' => '2026-07-22 06:32:47',
                'updated_at' => '2026-07-22 06:32:47',
            ],
            [
                'id_jadwal' => '6',
                'id_event' => '3',
                'tanggal' => '2025-12-11',
                'waktu_mulai' => '13:30:00',
                'waktu_selesai' => '15:30:00',
                'id_ruangan' => '3',
                'kelas' => 'B',
                'created_at' => '2026-07-22 06:32:47',
                'updated_at' => '2026-07-22 06:32:47',
            ],
            [
                'id_jadwal' => '7',
                'id_event' => '4',
                'tanggal' => '2025-12-05',
                'waktu_mulai' => '08:30:00',
                'waktu_selesai' => '10:30:00',
                'id_ruangan' => '4',
                'kelas' => 'A',
                'created_at' => '2026-07-22 06:32:47',
                'updated_at' => '2026-07-22 06:32:47',
            ],
            [
                'id_jadwal' => '8',
                'id_event' => '4',
                'tanggal' => '2025-12-12',
                'waktu_mulai' => '14:30:00',
                'waktu_selesai' => '16:30:00',
                'id_ruangan' => '4',
                'kelas' => 'B',
                'created_at' => '2026-07-22 06:32:47',
                'updated_at' => '2026-07-22 06:32:47',
            ],
            [
                'id_jadwal' => '9',
                'id_event' => '5',
                'tanggal' => '2025-12-06',
                'waktu_mulai' => '09:30:00',
                'waktu_selesai' => '11:30:00',
                'id_ruangan' => '5',
                'kelas' => 'A',
                'created_at' => '2026-07-22 06:32:47',
                'updated_at' => '2026-07-22 06:32:47',
            ],
            [
                'id_jadwal' => '10',
                'id_event' => '5',
                'tanggal' => '2025-12-13',
                'waktu_mulai' => '13:00:00',
                'waktu_selesai' => '15:00:00',
                'id_ruangan' => '5',
                'kelas' => 'B',
                'created_at' => '2026-07-22 06:32:47',
                'updated_at' => '2026-07-22 06:32:47',
            ],
            [
                'id_jadwal' => '11',
                'id_event' => '6',
                'tanggal' => '2025-12-07',
                'waktu_mulai' => '10:30:00',
                'waktu_selesai' => '12:30:00',
                'id_ruangan' => '6',
                'kelas' => 'A',
                'created_at' => '2026-07-22 06:32:47',
                'updated_at' => '2026-07-22 06:32:47',
            ],
            [
                'id_jadwal' => '12',
                'id_event' => '6',
                'tanggal' => '2025-12-14',
                'waktu_mulai' => '14:00:00',
                'waktu_selesai' => '16:00:00',
                'id_ruangan' => '6',
                'kelas' => 'B',
                'created_at' => '2026-07-22 06:32:47',
                'updated_at' => '2026-07-22 06:32:47',
            ],
            [
                'id_jadwal' => '13',
                'id_event' => '2',
                'tanggal' => '2026-07-30',
                'waktu_mulai' => '11:10:00',
                'waktu_selesai' => '01:00:00',
                'id_ruangan' => '5',
                'kelas' => 'B',
                'created_at' => '2026-07-30 03:43:33',
                'updated_at' => '2026-07-30 03:43:33',
            ],
        ];
        $this->db->table('jadwal')->insertBatch($data_jadwal);

        $this->db->table('berita')->truncate();
        $data_berita = [
            [
                'id_berita' => '1',
                'judul' => 'Workshop Pengembangan Aplikasi Web Modern',
                'konten' => 'Jurusan Informatika akan mengadakan workshop pengembangan aplikasi web modern menggunakan teknologi terbaru. Workshop ini akan diadakan pada tanggal 15 Desember 2024.',
                'kategori' => 'workshop',
                'tanggal' => '2024-12-15',
                'id_user' => '1',
                'created_at' => '2026-07-22 06:32:51',
                'updated_at' => '2026-07-22 06:32:51',
            ],
            [
                'id_berita' => '2',
                'judul' => 'Seminar Nasional Teknologi Informasi 2024',
                'konten' => 'Seminar nasional akan menghadirkan pembicara dari berbagai perusahaan teknologi terkemuka. Acara ini terbuka untuk mahasiswa dan dosen.',
                'kategori' => 'seminar',
                'tanggal' => '2024-11-20',
                'id_user' => '1',
                'created_at' => '2026-07-22 06:32:51',
                'updated_at' => '2026-07-22 06:32:51',
            ],
            [
                'id_berita' => '3',
                'judul' => 'Pengumuman Jadwal Ujian Akhir Semester',
                'konten' => 'Jadwal ujian akhir semester ganjil tahun akademik 2024/2025 telah diumumkan. Mahasiswa diharapkan memeriksa jadwal masing-masing.',
                'kategori' => 'pengumuman',
                'tanggal' => '2024-12-01',
                'id_user' => '1',
                'created_at' => '2026-07-22 06:32:51',
                'updated_at' => '2026-07-22 06:32:51',
            ],
            [
                'id_berita' => '4',
                'judul' => 'Kegiatan Internal: Rapat Koordinasi Dosen',
                'konten' => 'Rapat koordinasi dosen akan diadakan untuk membahas kurikulum dan program kerja semester depan.',
                'kategori' => 'internal',
                'tanggal' => '2024-12-10',
                'id_user' => '1',
                'created_at' => '2026-07-22 06:32:51',
                'updated_at' => '2026-07-22 06:32:51',
            ],
        ];
        $this->db->table('berita')->insertBatch($data_berita);

        $this->db->table('galeri_umum')->truncate();
        $data_galeri_umum = [
            [
                'id_galeri' => '1',
                'kategori' => 'foto',
                'keterangan' => 'Foto kegiatan praktikum di laboratorium komputer',
                'file_url' => '1785300087_d36bb0ea2103f0caae01.png',
                'tanggal_upload' => '2026-07-29',
                'id_user' => '1',
            ],
            [
                'id_galeri' => '2',
                'kategori' => 'foto',
                'keterangan' => 'Video dokumentasi seminar teknologi informasi',
                'file_url' => '1785300330_7bd3050164ad088b4c25.png',
                'tanggal_upload' => '2026-07-29',
                'id_user' => '1',
            ],
        ];
        $this->db->table('galeri_umum')->insertBatch($data_galeri_umum);

        $this->db->table('modul_praktikum')->truncate();
        $data_modul_praktikum = [
            [
                'id_modul' => '1',
                'judul' => 'Modul Praktikum Algoritma dan Pemrograman',
                'deskripsi' => 'Modul praktikum untuk mata kuliah Algoritma dan Pemrograman semester 1',
                'file_url' => '1785303420_be8b5d859251a59a3a6b.pdf',
                'id_jadwal' => '1',
                'created_at' => '2026-07-22 06:32:52',
                'updated_at' => '2026-07-29 05:37:00',
            ],
            [
                'id_modul' => '2',
                'judul' => 'Modul Praktikum Struktur Data',
                'deskripsi' => 'Modul praktikum untuk mata kuliah Struktur Data semester 2',
                'file_url' => '1785303433_4dc31db547c76803371b.docx',
                'id_jadwal' => '2',
                'created_at' => '2026-07-22 06:32:52',
                'updated_at' => '2026-07-29 05:37:13',
            ],
            [
                'id_modul' => '3',
                'judul' => 'Modul Praktikum Basis Data',
                'deskripsi' => 'Modul praktikum untuk mata kuliah Basis Data semester 3',
                'file_url' => '1785303441_c2cbbd3e1b626915c215.docx',
                'id_jadwal' => '3',
                'created_at' => '2026-07-22 06:32:52',
                'updated_at' => '2026-07-29 05:37:21',
            ],
            [
                'id_modul' => '4',
                'judul' => 'Modul Praktikum Pemrograman Web',
                'deskripsi' => 'Modul praktikum untuk mata kuliah Pemrograman Web semester 4',
                'file_url' => '1785303448_0c2663b3bb91fef0fc29.pdf',
                'id_jadwal' => '4',
                'created_at' => '2026-07-22 06:32:52',
                'updated_at' => '2026-07-29 05:37:28',
            ],
        ];
        $this->db->table('modul_praktikum')->insertBatch($data_modul_praktikum);

        $this->db->table('content_visi_misi')->truncate();
        $data_content_visi_misi = [
            [
                'id' => '1',
                'judul' => 'Visi',
                'isi' => 'To become a center of excellence in the development of smart systems and information processing technology that is innovative, adaptive, and applicable to the needs of society and data-based industry.',
                'created_at' => null,
                'updated_at' => '2026-07-22 06:32:53',
            ],
            [
                'id' => '2',
                'judul' => 'Misi',
                'isi' => '1. Organizing educational and practical activities based on smart systems and information processing.
2. Carrying out innovative research in the fields of AI, machine learning, deep learning, data mining, IR, NLP, and expert systems.
3. Providing a collaborative platform for lecturers, students, and industry to develop smart data-based solutions.
4. Encourage scientific publications, research products, and patents based on exploration results in the field of smart systems and data processing.
5. Building a project-based learning ecosystem that is relevant to the needs of the global workplace and research world.',
                'created_at' => null,
                'updated_at' => '2026-07-22 06:32:53',
            ],
        ];
        $this->db->table('content_visi_misi')->insertBatch($data_content_visi_misi);

        $this->db->table('publikasi')->truncate();
        $data_publikasi = [
            [
                'id_publikasi' => '1',
                'jenis_publikasi' => 'jurnal',
                'judul' => 'pengembangan',
                'link_publikasi' => 'https://doi.org/10.1000/example1',
                'kategori' => 'Jurnal Nasional',
                'topik' => 'machine learning',
                'tanggal_publikasi' => '2024-01-15',
                'penulis_pendamping' => '',
                'volume' => '15',
                'nomor' => '3',
                'tahun' => '2024',
                'link_doi' => 'https://doi.org/10.1000/example1',
                'link_gdrive' => 'https://drive.google.com/file/example1',
                'conference' => '',
                'deskripsi' => 'Penelitian ini membahas penerapan teknologi informasi...',
                'id_user' => '1',
                'created_at' => '2026-07-22 06:33:15',
                'updated_at' => '2026-07-28 10:28:01',
                'lokasi_conference' => null,
                'publisher_jurnal' => null,
            ],
        ];
        $this->db->table('publikasi')->insertBatch($data_publikasi);

        $this->db->table('project_lab')->truncate();
        $data_project_lab = [
            [
                'id_project' => '1',
                'judul' => 'Sistem Deteksi Hama Tanaman dengan CNN',
                'deskripsi' => 'Mengembangkan aplikasi mobile berbasis AI untuk mendeteksi jenis hama pada tanaman padi menggunakan metode Convolutional Neural Network.',
                'topik' => 'deep learning',
                'status' => 'sedang dilaksanakan',
                'teknologi' => 'Python, TensorFlow, Flutter',
                'link_repository' => 'https://github.com/lab-ti/deteksi-hama',
                'link_deploy' => null,
                'tanggal_mulai' => '2023-10-01',
                'tanggal_selesai' => null,
                'created_by' => '1',
                'created_at' => '2026-07-22 06:32:54',
                'updated_at' => '2026-07-22 06:32:54',
            ],
            [
                'id_project' => '2',
                'judul' => 'Smart Dashboard Monitoring Server Lab',
                'deskripsi' => 'Dashboard real-time untuk memantau suhu dan load server laboratorium menggunakan ESP32.',
                'topik' => 'smart system',
                'status' => 'selesai',
                'teknologi' => 'Laravel, VueJS, MQTT, C++',
                'link_repository' => 'https://github.com/lab-ti/smart-server',
                'link_deploy' => 'https://dashboard.lab-ti.ac.id',
                'tanggal_mulai' => '2023-01-15',
                'tanggal_selesai' => '2023-06-20',
                'created_by' => '1',
                'created_at' => '2026-07-22 06:32:54',
                'updated_at' => '2026-07-22 06:32:54',
            ],
            [
                'id_project' => '3',
                'judul' => 'Sistem Deteksi Hama Tanaman dengan CNN',
                'deskripsi' => 'Mengembangkan aplikasi mobile berbasis AI untuk mendeteksi jenis hama pada tanaman padi menggunakan metode Convolutional Neural Network.',
                'topik' => 'deep learning',
                'status' => 'sedang dilaksanakan',
                'teknologi' => 'Python, TensorFlow, Flutter',
                'link_repository' => 'https://github.com/lab-ti/deteksi-hama',
                'link_deploy' => '',
                'tanggal_mulai' => '2023-10-01',
                'tanggal_selesai' => '0000-00-00',
                'created_by' => '1',
                'created_at' => '2026-07-22 06:33:16',
                'updated_at' => '2026-07-22 06:33:16',
            ],
            [
                'id_project' => '4',
                'judul' => 'Smart Dashboard Monitoring Server Lab',
                'deskripsi' => 'Dashboard real-time untuk memantau suhu dan load server laboratorium menggunakan ESP32.',
                'topik' => 'smart system',
                'status' => 'selesai',
                'teknologi' => 'Laravel, VueJS, MQTT, C++',
                'link_repository' => 'https://github.com/lab-ti/smart-server',
                'link_deploy' => 'https://dashboard.lab-ti.ac.id',
                'tanggal_mulai' => '2023-01-15',
                'tanggal_selesai' => '2023-06-20',
                'created_by' => '1',
                'created_at' => '2026-07-22 06:33:16',
                'updated_at' => '2026-07-22 06:33:16',
            ],
            [
                'id_project' => '5',
                'judul' => 'pengembangan IOT dengan ML',
                'deskripsi' => 'Pengembangan untuk klasifikasi penyakit tanaman ',
                'topik' => 'machine learning',
                'status' => 'akan dilaksanakan',
                'teknologi' => 'Python, TensorFlow, Flutter',
                'link_repository' => '',
                'link_deploy' => '',
                'tanggal_mulai' => '0000-00-00',
                'tanggal_selesai' => '0000-00-00',
                'created_by' => '1',
                'created_at' => null,
                'updated_at' => null,
            ],
        ];
        $this->db->table('project_lab')->insertBatch($data_project_lab);

        $this->db->table('proyek_riset')->truncate();
        $data_proyek_riset = [
            [
                'id_proyek' => '1',
                'judul' => 'Pengembangan Sistem Informasi Akademik Berbasis Web',
                'topik' => 'smart system',
                'deskripsi' => 'Penelitian untuk mengembangkan sistem informasi akademik...',
                'mitra' => 'Universitas Indonesia',
                'sumber_dana' => 'DIKTI',
                'tahun_mulai' => '2024',
                'tahun_selesai' => '2026',
                'status' => 'sedang dilaksanakan',
                'id_user' => '1',
                'created_at' => '2026-07-22 06:33:17',
                'updated_at' => '2026-07-22 06:33:17',
            ],
            [
                'id_proyek' => '5',
                'judul' => 'pengembangan IOT dengan DL',
                'topik' => 'deep learning',
                'deskripsi' => 'pengembangan sistem IOT untuk tanaman dengan DL sebagai klasifikasi penyakit',
                'mitra' => '',
                'sumber_dana' => 'DIKTI',
                'tahun_mulai' => '2026',
                'tahun_selesai' => '2027',
                'status' => 'akan dilaksanakan',
                'id_user' => '1',
                'created_at' => '2026-07-30 03:02:43',
                'updated_at' => '2026-07-30 03:02:43',
            ],
        ];
        $this->db->table('proyek_riset')->insertBatch($data_proyek_riset);

        $this->db->table('rekrut')->truncate();
        $data_rekrut = [
            [
                'id_rekrut' => '1',
                'id_user' => '1',
                'id_jadwal' => '1',
                'deskripsi' => 'Rekrutmen Asisten Praktikum Algoritma dan Pemrograman',
                'status' => 'dibuka',
                'syarat' => 'Minimal IPK 3.5, Lulus mata kuliah Algoritma dan Pemrograman dengan nilai minimal B',
                'link_gform' => 'https://forms.google.com/your-form-link-here',
                'created_at' => '2026-07-22 06:32:58',
                'updated_at' => '2026-07-22 06:32:58',
            ],
            [
                'id_rekrut' => '2',
                'id_user' => '1',
                'id_jadwal' => '2',
                'deskripsi' => 'Rekrutmen Asisten Praktikum Struktur Data',
                'status' => 'dibuka',
                'syarat' => 'Minimal IPK 3.3, Lulus mata kuliah Struktur Data dengan nilai minimal B+',
                'link_gform' => 'https://forms.google.com/your-form-link-here',
                'created_at' => '2026-07-22 06:32:58',
                'updated_at' => '2026-07-22 06:32:58',
            ],
            [
                'id_rekrut' => '3',
                'id_user' => '1',
                'id_jadwal' => '3',
                'deskripsi' => 'Rekrutmen Asisten Praktikum Basis Data',
                'status' => 'ditutup',
                'syarat' => 'Minimal IPK 3.0, Lulus mata kuliah Basis Data dengan nilai minimal B',
                'link_gform' => 'https://forms.google.com/your-form-link-here',
                'created_at' => '2026-07-22 06:32:58',
                'updated_at' => '2026-07-22 06:32:58',
            ],
        ];
        $this->db->table('rekrut')->insertBatch($data_rekrut);

        $this->db->table('asisten_jadwal')->truncate();
        $data_asisten_jadwal = [
            [
                'id' => '1',
                'id_jadwal' => '1',
                'id_user' => '6',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '2',
                'id_jadwal' => '3',
                'id_user' => '7',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '3',
                'id_jadwal' => '5',
                'id_user' => '8',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '4',
                'id_jadwal' => '7',
                'id_user' => '9',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '5',
                'id_jadwal' => '9',
                'id_user' => '10',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '6',
                'id_jadwal' => '11',
                'id_user' => '11',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '8',
                'id_jadwal' => '4',
                'id_user' => '13',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '9',
                'id_jadwal' => '6',
                'id_user' => '14',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '10',
                'id_jadwal' => '8',
                'id_user' => '15',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '11',
                'id_jadwal' => '10',
                'id_user' => '16',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '12',
                'id_jadwal' => '12',
                'id_user' => '17',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '17',
                'id_jadwal' => '2',
                'id_user' => '9',
                'created_at' => null,
                'updated_at' => null,
            ],
        ];
        $this->db->table('asisten_jadwal')->insertBatch($data_asisten_jadwal);

        $this->db->table('asisten_periode')->truncate();
        $data_asisten_periode = [
            [
                'id' => '1',
                'id_user' => '6',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '2',
                'id_user' => '7',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '3',
                'id_user' => '8',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '4',
                'id_user' => '9',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '5',
                'id_user' => '10',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '6',
                'id_user' => '11',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '7',
                'id_user' => '12',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '8',
                'id_user' => '13',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '9',
                'id_user' => '14',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '10',
                'id_user' => '15',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '11',
                'id_user' => '16',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '12',
                'id_user' => '17',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '13',
                'id_user' => '18',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '14',
                'id_user' => '19',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '15',
                'id_user' => '20',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '16',
                'id_user' => '21',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '17',
                'id_user' => '22',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '18',
                'id_user' => '23',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '19',
                'id_user' => '24',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-29 07:30:30',
            ],
            [
                'id' => '20',
                'id_user' => '25',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
            [
                'id' => '21',
                'id_user' => '26',
                'id_periode' => '4',
                'jabatan' => 'Asisten Praktikum',
                'status_tugas' => 'belum selesai',
                'created_at' => '2026-07-22 06:33:10',
                'updated_at' => '2026-07-22 06:33:10',
            ],
        ];
        $this->db->table('asisten_periode')->insertBatch($data_asisten_periode);

        $this->db->table('role_permissions')->truncate();
        $data_role_permissions = [
            [
                'id' => '7',
                'role_id' => '2',
                'menu_key' => 'galeri_admin',
            ],
            [
                'id' => '8',
                'role_id' => '2',
                'menu_key' => 'jadwal_admin',
            ],
            [
                'id' => '9',
                'role_id' => '2',
                'menu_key' => 'jadwal_saya',
            ],
            [
                'id' => '10',
                'role_id' => '2',
                'menu_key' => 'sertifikat_klaim',
            ],
            [
                'id' => '5',
                'role_id' => '3',
                'menu_key' => 'penelitian_proyek_admin',
            ],
            [
                'id' => '4',
                'role_id' => '3',
                'menu_key' => 'project_lab_admin',
            ],
            [
                'id' => '6',
                'role_id' => '3',
                'menu_key' => 'publikasi_ilmiah_admin',
            ],
        ];
        $this->db->table('role_permissions')->insertBatch($data_role_permissions);

        $this->db->table('config_sertifikat')->truncate();
        $data_config_sertifikat = [
            [
                'id' => '1',
                'template_gambar' => 'sertifikat/template_1785303938.png',
                'judul' => 'SERTIFIKAT APRESIASI',
                'deskripsi_template' => 'telah berdidikasi sebagai asisten laboratorium PCD',
                'nama_kepala_lab' => 'Jasman Pardede',
                'ttd_kepala_lab' => null,
                'nama_ketua_prodi' => 'Dr. sc. Lisa Kristiana, ST., MT.',
                'ttd_ketua_prodi' => null,
                'updated_at' => '2026-07-29 05:45:38',
            ],
        ];
        $this->db->table('config_sertifikat')->insertBatch($data_config_sertifikat);

        $this->db->query('SET FOREIGN_KEY_CHECKS=1;');
    }
}
