<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class JadwalSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id_event'   => 1,
                'tanggal'    => '2025-08-01',
                'waktu_mulai'  => '08:00:00',
                'waktu_selesai'=> '10:00:00',
                'ruangan'      => 'Lab 1',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2025-08-05',
                'waktu_mulai'  => '13:00:00',
                'waktu_selesai'=> '15:00:00',
                'ruangan'      => 'Aula',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2025-08-10',
                'waktu_mulai'  => '09:00:00',
                'waktu_selesai'=> '11:00:00',
                'ruangan'      => 'Lab 2',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2025-08-15',
                'waktu_mulai'  => '14:00:00',
                'waktu_selesai'=> '16:00:00',
                'ruangan'      => 'Lab 3',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            // Additional schedule data
            [
                'id_event'   => 2,
                'tanggal'    => '2025-08-20',
                'waktu_mulai'  => '09:30:00',
                'waktu_selesai'=> '11:30:00',
                'ruangan'      => 'Lab Komputer 1',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2025-08-25',
                'waktu_mulai'  => '14:00:00',
                'waktu_selesai'=> '16:00:00',
                'ruangan'      => 'Lab Fisika Dasar',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2025-08-30',
                'waktu_mulai'  => '10:00:00',
                'waktu_selesai'=> '12:00:00',
                'ruangan'      => 'Lab 4',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2025-09-05',
                'waktu_mulai'  => '08:30:00',
                'waktu_selesai'=> '10:30:00',
                'ruangan'      => 'Aula Utama',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2025-09-10',
                'waktu_mulai'  => '13:00:00',
                'waktu_selesai'=> '15:00:00',
                'ruangan'      => 'Lab Multimedia',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2025-09-15',
                'waktu_mulai'  => '09:00:00',
                'waktu_selesai'=> '11:00:00',
                'ruangan'      => 'Lab Jaringan',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2025-09-20',
                'waktu_mulai'  => '14:30:00',
                'waktu_selesai'=> '16:30:00',
                'ruangan'      => 'Lab 2',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2025-09-25',
                'waktu_mulai'  => '10:30:00',
                'waktu_selesai'=> '12:30:00',
                'ruangan'      => 'Lab Robotika',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2025-09-30',
                'waktu_mulai'  => '08:00:00',
                'waktu_selesai'=> '10:00:00',
                'ruangan'      => 'Lab 1',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2025-10-05',
                'waktu_mulai'  => '13:30:00',
                'waktu_selesai'=> '15:30:00',
                'ruangan'      => 'Aula',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2025-10-10',
                'waktu_mulai'  => '09:00:00',
                'waktu_selesai'=> '11:00:00',
                'ruangan'      => 'Lab 3',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2025-10-15',
                'waktu_mulai'  => '14:00:00',
                'waktu_selesai'=> '16:00:00',
                'ruangan'      => 'Lab Komputer 2',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2025-10-20',
                'waktu_mulai'  => '08:30:00',
                'waktu_selesai'=> '10:30:00',
                'ruangan'      => 'Lab Fisika Dasar',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2025-10-25',
                'waktu_mulai'  => '13:00:00',
                'waktu_selesai'=> '15:00:00',
                'ruangan'      => 'Lab 4',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2025-10-30',
                'waktu_mulai'  => '09:30:00',
                'waktu_selesai'=> '11:30:00',
                'ruangan'      => 'Lab Jaringan',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2025-11-05',
                'waktu_mulai'  => '14:00:00',
                'waktu_selesai'=> '16:00:00',
                'ruangan'      => 'Aula Utama',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2025-11-10',
                'waktu_mulai'  => '10:00:00',
                'waktu_selesai'=> '12:00:00',
                'ruangan'      => 'Lab Multimedia',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2025-11-15',
                'waktu_mulai'  => '08:00:00',
                'waktu_selesai'=> '10:00:00',
                'ruangan'      => 'Lab Robotika',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2025-11-20',
                'waktu_mulai'  => '13:30:00',
                'waktu_selesai'=> '15:30:00',
                'ruangan'      => 'Lab 1',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2025-11-25',
                'waktu_mulai'  => '09:00:00',
                'waktu_selesai'=> '11:00:00',
                'ruangan'      => 'Lab 2',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2025-11-30',
                'waktu_mulai'  => '14:30:00',
                'waktu_selesai'=> '16:30:00',
                'ruangan'      => 'Lab 3',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2025-12-05',
                'waktu_mulai'  => '08:30:00',
                'waktu_selesai'=> '10:30:00',
                'ruangan'      => 'Lab Fisika Dasar',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2025-12-10',
                'waktu_mulai'  => '13:00:00',
                'waktu_selesai'=> '15:00:00',
                'ruangan'      => 'Lab 4',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2025-12-15',
                'waktu_mulai'  => '09:30:00',
                'waktu_selesai'=> '11:30:00',
                'ruangan'      => 'Lab Jaringan',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2025-12-20',
                'waktu_mulai'  => '14:00:00',
                'waktu_selesai'=> '16:00:00',
                'ruangan'      => 'Aula',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2025-12-25',
                'waktu_mulai'  => '10:00:00',
                'waktu_selesai'=> '12:00:00',
                'ruangan'      => 'Lab Multimedia',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            // Additional Indonesian schedule data
            [
                'id_event'   => 1,
                'tanggal'    => '2025-12-30',
                'waktu_mulai'  => '08:00:00',
                'waktu_selesai'=> '10:00:00',
                'ruangan'      => 'Lab Komputer 3',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2026-01-05',
                'waktu_mulai'  => '13:00:00',
                'waktu_selesai'=> '15:00:00',
                'ruangan'      => 'Gedung Serba Guna',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2026-01-10',
                'waktu_mulai'  => '09:00:00',
                'waktu_selesai'=> '11:00:00',
                'ruangan'      => 'Lab Jaringan Komputer',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2026-01-15',
                'waktu_mulai'  => '14:00:00',
                'waktu_selesai'=> '16:00:00',
                'ruangan'      => 'Lab Basis Data',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2026-01-20',
                'waktu_mulai'  => '09:30:00',
                'waktu_selesai'=> '11:30:00',
                'ruangan'      => 'Lab Pemrograman',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2026-01-25',
                'waktu_mulai'  => '14:00:00',
                'waktu_selesai'=> '16:00:00',
                'ruangan'      => 'Lab Sistem Informasi',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2026-01-30',
                'waktu_mulai'  => '10:00:00',
                'waktu_selesai'=> '12:00:00',
                'ruangan'      => 'Lab Multimedia',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2026-02-05',
                'waktu_mulai'  => '08:30:00',
                'waktu_selesai'=> '10:30:00',
                'ruangan'      => 'Aula Rektorat',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2026-02-10',
                'waktu_mulai'  => '13:00:00',
                'waktu_selesai'=> '15:00:00',
                'ruangan'      => 'Lab Keamanan Jaringan',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2026-02-15',
                'waktu_mulai'  => '09:00:00',
                'waktu_selesai'=> '11:00:00',
                'ruangan'      => 'Lab Sistem Cerdas',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2026-02-20',
                'waktu_mulai'  => '14:30:00',
                'waktu_selesai'=> '16:30:00',
                'ruangan'      => 'Lab Komputer 4',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2026-02-25',
                'waktu_mulai'  => '10:30:00',
                'waktu_selesai'=> '12:30:00',
                'ruangan'      => 'Lab Pengolahan Citra',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2026-03-02',
                'waktu_mulai'  => '08:00:00',
                'waktu_selesai'=> '10:00:00',
                'ruangan'      => 'Lab Komputer 1',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2026-03-07',
                'waktu_mulai'  => '13:30:00',
                'waktu_selesai'=> '15:30:00',
                'ruangan'      => 'Gedung Kuliah Bersama',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2026-03-12',
                'waktu_mulai'  => '09:00:00',
                'waktu_selesai'=> '11:00:00',
                'ruangan'      => 'Lab Robotika',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2026-03-17',
                'waktu_mulai'  => '14:00:00',
                'waktu_selesai'=> '16:00:00',
                'ruangan'      => 'Lab Pemrograman Mobile',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2026-03-22',
                'waktu_mulai'  => '08:30:00',
                'waktu_selesai'=> '10:30:00',
                'ruangan'      => 'Lab Fisika Dasar',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2026-03-27',
                'waktu_mulai'  => '13:00:00',
                'waktu_selesai'=> '15:00:00',
                'ruangan'      => 'Lab Komputer 2',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2026-04-01',
                'waktu_mulai'  => '09:30:00',
                'waktu_selesai'=> '11:30:00',
                'ruangan'      => 'Lab Jaringan',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2026-04-06',
                'waktu_mulai'  => '14:00:00',
                'waktu_selesai'=> '16:00:00',
                'ruangan'      => 'Aula Utama',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2026-04-11',
                'waktu_mulai'  => '10:00:00',
                'waktu_selesai'=> '12:00:00',
                'ruangan'      => 'Lab Sistem Terdistribusi',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2026-04-16',
                'waktu_mulai'  => '08:00:00',
                'waktu_selesai'=> '10:00:00',
                'ruangan'      => 'Lab Basis Data',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2026-04-21',
                'waktu_mulai'  => '13:30:00',
                'waktu_selesai'=> '15:30:00',
                'ruangan'      => 'Lab Komputer 3',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2026-04-26',
                'waktu_mulai'  => '09:00:00',
                'waktu_selesai'=> '11:00:00',
                'ruangan'      => 'Lab Pengembangan Web',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2026-05-01',
                'waktu_mulai'  => '14:30:00',
                'waktu_selesai'=> '16:30:00',
                'ruangan'      => 'Lab Sistem Informasi',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2026-05-06',
                'waktu_mulai'  => '08:30:00',
                'waktu_selesai'=> '10:30:00',
                'ruangan'      => 'Lab Fisika Dasar',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2026-05-11',
                'waktu_mulai'  => '13:00:00',
                'waktu_selesai'=> '15:00:00',
                'ruangan'      => 'Lab Komputer 4',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 1,
                'tanggal'    => '2026-05-16',
                'waktu_mulai'  => '09:30:00',
                'waktu_selesai'=> '11:30:00',
                'ruangan'      => 'Lab Jaringan',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 2,
                'tanggal'    => '2026-05-21',
                'waktu_mulai'  => '14:00:00',
                'waktu_selesai'=> '16:00:00',
                'ruangan'      => 'Aula',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
            [
                'id_event'   => 3,
                'tanggal'    => '2026-05-26',
                'waktu_mulai'  => '10:00:00',
                'waktu_selesai'=> '12:00:00',
                'ruangan'      => 'Lab Multimedia',
                'created_at'   => date('Y-m-d H:i:s'),
                'updated_at'   => date('Y-m-d H:i:s'),
            ],
        ];

        // Check if jadwal already exist
        foreach ($data as $jadwal) {
            $existing = $this->db->table('jadwal')->where('id_event', $jadwal['id_event'])->where('tanggal', $jadwal['tanggal'])->get()->getRow();
            if (!$existing) {
                $this->db->table('jadwal')->insert($jadwal);
            }
        }
    }
}