<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PublikasiSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'jenis_publikasi' => 'jurnal',
                'link_publikasi' => 'https://doi.org/10.1000/example1',
                'kategori' => 'Jurnal Nasional',
                'tanggal_publikasi' => '2024-01-15',
                'id_user' => 1,
                'penulis_pendamping' => 'Dr. Budi Santoso, M.Kom',
                'volume' => '15',
                'nomor' => '3',
                'tahun' => '2024',
                'link_doi' => 'https://doi.org/10.1000/example1',
                'link_gdrive' => 'https://drive.google.com/file/example1',
                'deskripsi' => 'Penelitian ini membahas penerapan teknologi informasi dalam pengembangan sistem akademik di perguruan tinggi Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'prosiding',
                'link_publikasi' => 'https://ieeexplore.ieee.org/example2',
                'kategori' => 'Konferensi Internasional',
                'tanggal_publikasi' => '2024-03-20',
                'id_user' => 2,
                'penulis_pendamping' => 'Dr. Siti Nurhaliza, S.T., M.T.',
                'conference' => 'International Conference on Computer Science and Technology (ICCSAT) 2024',
                'tahun' => '2024',
                'link_doi' => 'https://doi.org/10.1109/ICCSAT2024.123456',
                'link_gdrive' => 'https://drive.google.com/file/example2',
                'deskripsi' => 'Makalah ini mempresentasikan hasil penelitian tentang algoritma optimasi untuk pengolahan data besar dalam sistem komputasi terdistribusi.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'paten',
                'link_publikasi' => 'https://patents.google.com/example3',
                'kategori' => 'Paten Sederhana',
                'tanggal_publikasi' => '2024-06-10',
                'id_user' => 3,
                'penulis_pendamping' => 'Prof. Ahmad Rizki, Ph.D.',
                'tahun' => '2024',
                'link_doi' => 'https://doi.org/10.1000/paten123',
                'link_gdrive' => 'https://drive.google.com/file/example3',
                'deskripsi' => 'Paten ini menjelaskan sistem inovatif untuk pengelolaan energi terbarukan berbasis mikrokontroler yang dapat diterapkan di daerah terpencil.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // Additional Indonesian publication data
            [
                'jenis_publikasi' => 'jurnal',
                'link_publikasi' => 'https://jurnal.universitas-indonesia.ac.id/index.php/jtki/article/view/12345',
                'kategori' => 'Jurnal Nasional Terakreditasi',
                'tanggal_publikasi' => '2024-02-10',
                'id_user' => 4,
                'penulis_pendamping' => 'Dr. Dewi Sartika, S.Kom., M.Kom.',
                'volume' => '12',
                'nomor' => '1',
                'tahun' => '2024',
                'link_doi' => 'https://doi.org/10.12345/jtki.2024.12.1.001',
                'link_gdrive' => 'https://drive.google.com/file/jurnal1',
                'deskripsi' => 'Analisis penerapan machine learning untuk prediksi kualitas udara di kota-kota besar Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'prosiding',
                'link_publikasi' => 'https://prosiding.stt-telekomunikasi.ac.id/seminar2024/paper001',
                'kategori' => 'Seminar Nasional',
                'tanggal_publikasi' => '2024-05-15',
                'id_user' => 5,
                'penulis_pendamping' => 'Ir. Rizki Pratama, M.T.',
                'conference' => 'Seminar Nasional Teknologi Informasi dan Komunikasi 2024 (SENTIKA)',
                'tahun' => '2024',
                'link_doi' => 'https://doi.org/10.5555/sentika.2024.001',
                'link_gdrive' => 'https://drive.google.com/file/seminar1',
                'deskripsi' => 'Implementasi blockchain untuk sistem voting elektronik berbasis mobile di Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'jurnal',
                'link_publikasi' => 'https://ejournal.universitas-gadjah-mada.ac.id/index.php/teknotel/article/view/67890',
                'kategori' => 'Jurnal Internasional',
                'tanggal_publikasi' => '2024-04-22',
                'id_user' => 6,
                'penulis_pendamping' => 'Prof. Nina Safitri, Ph.D.',
                'volume' => '20',
                'nomor' => '2',
                'tahun' => '2024',
                'link_doi' => 'https://doi.org/10.1016/j.teknotel.2024.101234',
                'link_gdrive' => 'https://drive.google.com/file/jurnal2',
                'deskripsi' => 'Pengembangan sistem IoT untuk monitoring kualitas air sungai di wilayah Jawa.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'paten',
                'link_publikasi' => 'https://patents.google.com/patent/ID123456789A',
                'kategori' => 'Paten Nasional',
                'tanggal_publikasi' => '2024-07-18',
                'id_user' => 7,
                'penulis_pendamping' => 'Dr. Muhammad Fadli, S.T., M.T.',
                'tahun' => '2024',
                'link_doi' => 'https://doi.org/10.1000/paten456',
                'link_gdrive' => 'https://drive.google.com/file/paten1',
                'deskripsi' => 'Alat pemantau kesehatan berbasis sensor untuk deteksi dini penyakit jantung.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'prosiding',
                'link_publikasi' => 'https://prosiding.universitas-pancasila.ac.id/informatika2024/paper002',
                'kategori' => 'Workshop Nasional',
                'tanggal_publikasi' => '2024-08-05',
                'id_user' => 8,
                'penulis_pendamping' => 'Dr. Anisa Putri, S.Kom., M.T.',
                'conference' => 'Workshop Nasional Informatika Terapan 2024',
                'tahun' => '2024',
                'link_doi' => 'https://doi.org/10.7777/winit.2024.002',
                'link_gdrive' => 'https://drive.google.com/file/workshop1',
                'deskripsi' => 'Pemanfaatan augmented reality dalam aplikasi pembelajaran berbasis mobile untuk mahasiswa Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'jurnal',
                'link_publikasi' => 'https://journal.universitas-islam-bandung.ac.id/index.php/teknik/article/view/11111',
                'kategori' => 'Jurnal Nasional',
                'tanggal_publikasi' => '2024-03-30',
                'id_user' => 9,
                'penulis_pendamping' => 'Ir. Bambang Sutrisno, M.Sc.',
                'volume' => '18',
                'nomor' => '4',
                'tahun' => '2024',
                'link_doi' => 'https://doi.org/10.2222/teknik.2024.18.4.005',
                'link_gdrive' => 'https://drive.google.com/file/jurnal3',
                'deskripsi' => 'Optimasi algoritma genetika untuk penjadwalan perkuliahan di perguruan tinggi Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'prosiding',
                'link_publikasi' => 'https://prosiding.universitas-bina-nusantara.ac.id/komputer2024/paper003',
                'kategori' => 'Konferensi Internasional',
                'tanggal_publikasi' => '2024-09-12',
                'id_user' => 10,
                'penulis_pendamping' => 'Prof. Sarah Wijaya, Ph.D.',
                'conference' => 'International Conference on Computer Applications and Information Systems (ICCAIS) 2024',
                'tahun' => '2024',
                'link_doi' => 'https://doi.org/10.1109/ICCAIS2024.987654',
                'link_gdrive' => 'https://drive.google.com/file/conference1',
                'deskripsi' => 'Penerapan deep learning untuk analisis sentimen masyarakat terhadap kebijakan pemerintah di media sosial Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // More Indonesian publication data
            [
                'jenis_publikasi' => 'jurnal',
                'link_publikasi' => 'https://ejournal.universitas-indonesia.ac.id/index.php/jti/article/view/22222',
                'kategori' => 'Jurnal Nasional Terakreditasi',
                'tanggal_publikasi' => '2024-10-15',
                'id_user' => 11,
                'penulis_pendamping' => 'Dr. Andi Prasetyo, S.T., M.T.',
                'volume' => '14',
                'nomor' => '2',
                'tahun' => '2024',
                'link_doi' => 'https://doi.org/10.3333/jti.2024.14.2.002',
                'link_gdrive' => 'https://drive.google.com/file/jurnal4',
                'deskripsi' => 'Pengembangan model prediktif untuk curah hujan di wilayah Indonesia menggunakan teknik data mining.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'prosiding',
                'link_publikasi' => 'https://prosiding.stt-telekomunikasi.ac.id/seminar2024/paper004',
                'kategori' => 'Seminar Nasional',
                'tanggal_publikasi' => '2024-11-20',
                'id_user' => 12,
                'penulis_pendamping' => 'Ir. Siti Aminah, M.Kom.',
                'conference' => 'Seminar Nasional Informatika dan Teknologi 2024 (SINTA)',
                'tahun' => '2024',
                'link_doi' => 'https://doi.org/10.6666/sinta.2024.004',
                'link_gdrive' => 'https://drive.google.com/file/seminar2',
                'deskripsi' => 'Implementasi sistem e-learning berbasis cloud computing untuk perguruan tinggi di Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'paten',
                'link_publikasi' => 'https://patents.google.com/patent/ID987654321A',
                'kategori' => 'Paten Nasional',
                'tanggal_publikasi' => '2024-12-05',
                'id_user' => 13,
                'penulis_pendamping' => 'Prof. Bambang Susilo, Ph.D.',
                'tahun' => '2024',
                'link_doi' => 'https://doi.org/10.2000/paten789',
                'link_gdrive' => 'https://drive.google.com/file/paten2',
                'deskripsi' => 'Sistem otomatisasi pertanian berbasis IoT untuk meningkatkan produktivitas padi di Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'jurnal',
                'link_publikasi' => 'https://journal.universitas-gadjah-mada.ac.id/index.php/teknik/article/view/33333',
                'kategori' => 'Jurnal Internasional',
                'tanggal_publikasi' => '2025-01-10',
                'id_user' => 14,
                'penulis_pendamping' => 'Dr. Rina Kusuma, S.Si., M.Si.',
                'volume' => '22',
                'nomor' => '1',
                'tahun' => '2025',
                'link_doi' => 'https://doi.org/10.1016/j.teknik.2025.102345',
                'link_gdrive' => 'https://drive.google.com/file/jurnal5',
                'deskripsi' => 'Analisis kualitas air tanah di kawasan industri Indonesia menggunakan metode spektroskopi.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'prosiding',
                'link_publikasi' => 'https://prosiding.universitas-pancasila.ac.id/informatika2025/paper005',
                'kategori' => 'Workshop Nasional',
                'tanggal_publikasi' => '2025-02-15',
                'id_user' => 15,
                'penulis_pendamping' => 'Dr. Joko Susilo, S.Kom., M.T.',
                'conference' => 'Workshop Nasional Teknologi Informasi 2025',
                'tahun' => '2025',
                'link_doi' => 'https://doi.org/10.8888/wnti.2025.005',
                'link_gdrive' => 'https://drive.google.com/file/workshop2',
                'deskripsi' => 'Penerapan computer vision untuk sistem identifikasi jenis ikan di perairan Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'jurnal',
                'link_publikasi' => 'https://ejournal.universitas-indonesia.ac.id/index.php/jtki/article/view/44444',
                'kategori' => 'Jurnal Nasional Terakreditasi',
                'tanggal_publikasi' => '2025-03-20',
                'id_user' => 16,
                'penulis_pendamping' => 'Ir. Dwi Prasetyo, M.Sc.',
                'volume' => '16',
                'nomor' => '1',
                'tahun' => '2025',
                'link_doi' => 'https://doi.org/10.4444/jtki.2025.16.1.003',
                'link_gdrive' => 'https://drive.google.com/file/jurnal6',
                'deskripsi' => 'Optimasi penggunaan energi surya untuk sistem irigasi pertanian di wilayah Indonesia timur.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'paten',
                'link_publikasi' => 'https://patents.google.com/patent/ID456789123A',
                'kategori' => 'Paten Sederhana',
                'tanggal_publikasi' => '2025-04-25',
                'id_user' => 17,
                'penulis_pendamping' => 'Prof. Sri Wulandari, Ph.D.',
                'tahun' => '2025',
                'link_doi' => 'https://doi.org/10.3000/paten321',
                'link_gdrive' => 'https://drive.google.com/file/paten3',
                'deskripsi' => 'Alat deteksi dini banjir berbasis sensor ultrasonik untuk wilayah rawan banjir di Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'prosiding',
                'link_publikasi' => 'https://prosiding.stt-telekomunikasi.ac.id/seminar2025/paper006',
                'kategori' => 'Seminar Internasional',
                'tanggal_publikasi' => '2025-05-30',
                'id_user' => 18,
                'penulis_pendamping' => 'Dr. Agus Setiawan, S.T., M.T.',
                'conference' => 'International Seminar on Information Technology 2025 (ISIT)',
                'tahun' => '2025',
                'link_doi' => 'https://doi.org/10.9999/isit.2025.006',
                'link_gdrive' => 'https://drive.google.com/file/seminar3',
                'deskripsi' => 'Pemanfaatan big data analytics untuk meningkatkan kualitas layanan transportasi umum di kota-kota besar Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'jurnal',
                'link_publikasi' => 'https://journal.universitas-islam-bandung.ac.id/index.php/teknik/article/view/55555',
                'kategori' => 'Jurnal Nasional',
                'tanggal_publikasi' => '2025-06-15',
                'id_user' => 19,
                'penulis_pendamping' => 'Dr. Maya Dewi, S.T., M.T.',
                'volume' => '20',
                'nomor' => '3',
                'tahun' => '2025',
                'link_doi' => 'https://doi.org/10.5555/teknik.2025.20.3.007',
                'link_gdrive' => 'https://drive.google.com/file/jurnal7',
                'deskripsi' => 'Pengembangan material komposit berbasis serat alam untuk aplikasi konstruksi di Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'paten',
                'link_publikasi' => 'https://patents.google.com/patent/ID321654987A',
                'kategori' => 'Paten Nasional',
                'tanggal_publikasi' => '2025-07-20',
                'id_user' => 20,
                'penulis_pendamping' => 'Ir. Budi Santoso, M.Sc.',
                'tahun' => '2025',
                'link_doi' => 'https://doi.org/10.4000/paten654',
                'link_gdrive' => 'https://drive.google.com/file/paten4',
                'deskripsi' => 'Sistem pemantau kualitas udara berbasis sensor nirkabel untuk kota-kota besar di Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'jurnal',
                'link_publikasi' => 'https://ejournal.universitas-gadjah-mada.ac.id/index.php/teknotel/article/view/66666',
                'kategori' => 'Jurnal Internasional',
                'tanggal_publikasi' => '2025-08-25',
                'id_user' => 21,
                'penulis_pendamping' => 'Prof. Siti Nurhaliza, Ph.D.',
                'volume' => '24',
                'nomor' => '4',
                'tahun' => '2025',
                'link_doi' => 'https://doi.org/10.1016/j.teknotel.2025.103456',
                'link_gdrive' => 'https://drive.google.com/file/jurnal8',
                'deskripsi' => 'Penerapan teknologi 5G untuk sistem telemedicine di daerah terpencil Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'prosiding',
                'link_publikasi' => 'https://prosiding.universitas-pancasila.ac.id/informatika2025/paper007',
                'kategori' => 'Workshop Nasional',
                'tanggal_publikasi' => '2025-09-30',
                'id_user' => 22,
                'penulis_pendamping' => 'Dr. Rizki Pratama, S.Kom., M.T.',
                'conference' => 'Workshop Nasional Sistem Informasi 2025',
                'tahun' => '2025',
                'link_doi' => 'https://doi.org/10.1111/wsi.2025.007',
                'link_gdrive' => 'https://drive.google.com/file/workshop3',
                'deskripsi' => 'Implementasi sistem informasi geografis untuk pemantauan distribusi bantuan sosial di Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'jurnal',
                'link_publikasi' => 'https://jurnal.universitas-indonesia.ac.id/index.php/jti/article/view/77777',
                'kategori' => 'Jurnal Nasional Terakreditasi',
                'tanggal_publikasi' => '2025-10-15',
                'id_user' => 23,
                'penulis_pendamping' => 'Dr. Nina Safitri, S.T., M.T.',
                'volume' => '18',
                'nomor' => '4',
                'tahun' => '2025',
                'link_doi' => 'https://doi.org/10.7777/jti.2025.18.4.008',
                'link_gdrive' => 'https://drive.google.com/file/jurnal9',
                'deskripsi' => 'Analisis penerapan teknologi blockchain untuk sistem manajemen rantai pasok di Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'paten',
                'link_publikasi' => 'https://patents.google.com/patent/ID789456123A',
                'kategori' => 'Paten Sederhana',
                'tanggal_publikasi' => '2025-11-20',
                'id_user' => 24,
                'penulis_pendamping' => 'Prof. Ahmad Rizki, Ph.D.',
                'tahun' => '2025',
                'link_doi' => 'https://doi.org/10.5000/paten987',
                'link_gdrive' => 'https://drive.google.com/file/paten5',
                'deskripsi' => 'Alat pengolahan air limbah berbasis mikroba untuk komunitas pedesaan di Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'prosiding',
                'link_publikasi' => 'https://prosiding.stt-telekomunikasi.ac.id/seminar2025/paper008',
                'kategori' => 'Seminar Nasional',
                'tanggal_publikasi' => '2025-12-25',
                'id_user' => 25,
                'penulis_pendamping' => 'Ir. Muhammad Fadli, M.Sc.',
                'conference' => 'Seminar Nasional Teknologi Informasi dan Komunikasi 2025 (SENTIKA)',
                'tahun' => '2025',
                'link_doi' => 'https://doi.org/10.2222/sentika.2025.008',
                'link_gdrive' => 'https://drive.google.com/file/seminar4',
                'deskripsi' => 'Penerapan augmented reality untuk sistem navigasi indoor di pusat perbelanjaan Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'jurnal',
                'link_publikasi' => 'https://journal.universitas-islam-bandung.ac.id/index.php/teknik/article/view/88888',
                'kategori' => 'Jurnal Nasional',
                'tanggal_publikasi' => '2026-01-30',
                'id_user' => 26,
                'penulis_pendamping' => 'Dr. Anisa Putri, S.Si., M.Si.',
                'volume' => '22',
                'nomor' => '1',
                'tahun' => '2026',
                'link_doi' => 'https://doi.org/10.8888/teknik.2026.22.1.009',
                'link_gdrive' => 'https://drive.google.com/file/jurnal10',
                'deskripsi' => 'Optimasi desain turbin angin untuk kondisi geografis Indonesia menggunakan metode elemen hingga.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'paten',
                'link_publikasi' => 'https://patents.google.com/patent/ID159753468A',
                'kategori' => 'Paten Nasional',
                'tanggal_publikasi' => '2026-02-15',
                'id_user' => 27,
                'penulis_pendamping' => 'Prof. Bambang Sutrisno, Ph.D.',
                'tahun' => '2026',
                'link_doi' => 'https://doi.org/10.6000/paten456',
                'link_gdrive' => 'https://drive.google.com/file/paten6',
                'deskripsi' => 'Sistem deteksi dini gempa bumi berbasis sensor seismik untuk wilayah Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'prosiding',
                'link_publikasi' => 'https://prosiding.universitas-bina-nusantara.ac.id/komputer2026/paper009',
                'kategori' => 'Konferensi Internasional',
                'tanggal_publikasi' => '2026-03-20',
                'id_user' => 28,
                'penulis_pendamping' => 'Dr. Sarah Wijaya, S.T., M.T.',
                'conference' => 'International Conference on Computer Science and Information Technology (ICCSIT) 2026',
                'tahun' => '2026',
                'link_doi' => 'https://doi.org/10.3333/ICCSIT2026.987654',
                'link_gdrive' => 'https://drive.google.com/file/conference2',
                'deskripsi' => 'Penerapan deep learning untuk analisis citra satelit dalam pemantauan perubahan penggunaan lahan di Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'jurnal',
                'link_publikasi' => 'https://ejournal.universitas-indonesia.ac.id/index.php/jtki/article/view/99999',
                'kategori' => 'Jurnal Nasional Terakreditasi',
                'tanggal_publikasi' => '2026-04-25',
                'id_user' => 29,
                'penulis_pendamping' => 'Dr. Andi Prasetyo, S.Kom., M.Kom.',
                'volume' => '20',
                'nomor' => '2',
                'tahun' => '2026',
                'link_doi' => 'https://doi.org/10.9999/jtki.2026.20.2.010',
                'link_gdrive' => 'https://drive.google.com/file/jurnal11',
                'deskripsi' => 'Pengembangan model prediktif untuk harga komoditas pertanian di pasar Indonesia menggunakan machine learning.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'jenis_publikasi' => 'prosiding',
                'link_publikasi' => 'https://prosiding.universitas-pancasila.ac.id/informatika2026/paper010',
                'kategori' => 'Workshop Nasional',
                'tanggal_publikasi' => '2026-05-30',
                'id_user' => 30,
                'penulis_pendamping' => 'Ir. Siti Aminah, M.T.',
                'conference' => 'Workshop Nasional Informatika Terapan 2026',
                'tahun' => '2026',
                'link_doi' => 'https://doi.org/10.4444/winit.2026.010',
                'link_gdrive' => 'https://drive.google.com/file/workshop4',
                'deskripsi' => 'Pemanfaatan virtual reality dalam aplikasi pembelajaran berbasis mobile untuk mahasiswa teknik di Indonesia.',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        // Check if publikasi already exist
        foreach ($data as $publikasi) {
            $existing = $this->db->table('publikasi')->where('link_publikasi', $publikasi['link_publikasi'])->get()->getRow();
            if (!$existing) {
                $this->db->table('publikasi')->insert($publikasi);
            }
        }
    }
}